/**
 * routing plugin — opencode plugin
 *
 * Tool routing, security policy, and shell guidance.
 * Combines hooks/routing.js, hooks/tool-naming.js, hooks/guidance.js.
 *
 * Source of truth: ctx_plugin/src/routing-plugin.ts
 * Do not edit manually — generated by bin/build-plugins.mjs.
 */

import path from "node:path";
import os from "node:os";
import { existsSync, readFileSync } from "node:fs";

// Hooks — imported from co-located copies built alongside this plugin
import { normalizeToolName, isCtxPluginTool } from "./hooks/tool-naming.js";
import { routeTool } from "./hooks/routing.js";

// ─────────────────────────────────────────────────────────────────────────────
// MCP ready detection
// ─────────────────────────────────────────────────────────────────────────────

function checkMcpReady() {
    const configDir = process.env.OPENCODE_CONFIG_DIR ||
        (process.env.XDG_CONFIG_HOME && path.join(process.env.XDG_CONFIG_HOME, "opencode")) ||
        (process.platform === "win32"
            ? path.join(process.env.APPDATA || path.join(os.homedir(), "AppData", "Roaming"), "opencode")
            : path.join(os.homedir(), ".config", "opencode"));
    try {
        const configPath = path.join(configDir, "opencode.json");
        if (existsSync(configPath)) {
            const cfg = JSON.parse(readFileSync(configPath, "utf8"));
            if (cfg?.mcp?.ctx_plugin)
                return true;
        }
    }
    catch { }
    return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Security patterns for permission.ask hook (auto-grant / deny)
// Independent from routing-level patterns in hooks/routing.ts.
// ─────────────────────────────────────────────────────────────────────────────

const SAFE_PATTERNS = [
    /^git\s+(status|diff|log|branch|remote|tag|stash|pull|push)/,
    /^npm\s+(install|run|test|build|ci|outdated)/,
    /^pnpm\s+/,
    /^yarn\s+/,
    /^bun\s+/,
    /^cargo\s+/,
    /^go\s+(run|build|test|get)/,
    /^ls(?!\s+-[a-zA-Z]*R)/,
    /^pwd$/,
    /^whoami$/,
    /^echo\s/,
    /^mkdir\s/,
    /^touch\s/,
    /^cat\s/,
    /^grep\s/,
];

const DANGEROUS_PATTERNS = [
    /curl.*\|.*sh/i,
    /wget.*\|.*sh/i,
    /rm\s+-rf\s+\/(?!proc|sys|dev)/,
    /\beval\s*\(/,
    /PYTHONSTARTUP/,
    /LD_PRELOAD/,
];

function isSafeCommand(cmd) {
    return SAFE_PATTERNS.some(rx => rx.test(cmd.trim()));
}

function isDangerousCommand(cmd) {
    return DANGEROUS_PATTERNS.some(rx => rx.test(cmd));
}

// ─────────────────────────────────────────────────────────────────────────────
// Plugin factory
// ─────────────────────────────────────────────────────────────────────────────

export const RoutingPlugin = async (input) => {
    const mcpReady = checkMcpReady();
    const sessionId = String(input.sessionID ?? input.sessionId ?? process.pid);

    return {
        // Routing decision + security enforcement for all tool calls
        "tool.execute.before": async (input, output) => {
            const tool = String(input.tool ?? "").toLowerCase();
            const args = (output.args ?? {}) ?? {};

            const normalized = normalizeToolName(tool);
            if (!isCtxPluginTool(normalized)) {
                try {
                    const decision = routeTool({
                        tool,
                        args,
                        sessionId,
                        projectDir: input.directory ?? input.worktree,
                        mcpReady,
                    });

                    if (decision.action === "deny") {
                        throw new Error(`[ctx_plugin routing] ${decision.reason ?? "blocked by security policy"}`);
                    }
                    if (decision.action === "context" && decision.additionalContext) {
                        output.context = output.context ?? {};
                        if (typeof output.context === "object" && output.context !== null) {
                            output.context.__ctxPluginGuidance = decision.additionalContext;
                        }
                    }
                    if (decision.action === "modify" && decision.updatedArgs) {
                        Object.assign(args, decision.updatedArgs);
                    }
                }
                catch (err) {
                    if (err instanceof Error && err.message.startsWith("[ctx_plugin routing]"))
                        throw err;
                }
            }
        },

        // Verbose tool execution logging
        "tool.execute.after": async (input, output) => {
            if (process.env.CTX_PLUGIN_VERBOSE === "1") {
                const tool = String(input.tool ?? "");
                const args = (input.args ?? {}) ?? {};
                const title = output.title ?? tool;
                const outputText = typeof output.output === "string"
                    ? output.output.slice(0, 200)
                    : String(output.output).slice(0, 200);
                console.error(`[ctx_plugin] tool: ${title}, args: ${JSON.stringify(args).slice(0, 100)}, output: ${outputText}...`);
            }
        },

        // Inject CTX_PLUGIN_* into all shell sessions
        "shell.env": async (input, output) => {
            output.env = output.env ?? {};
            output.env["CTX_PLUGIN_VERSION"] = "0.3.0";
            output.env["CTX_PLUGIN_MCP_READY"] = mcpReady ? "1" : "0";
            if (input.directory) {
                output.env["CTX_PROJECT_DIR"] = input.directory;
            }
        },

        // Permission gate: auto-grant safe, deny dangerous
        "permission.ask": async (input, output) => {
            const perm = input;
            const ptype = perm.permission?.type ?? "";
            const pcmd = perm.permission?.command ?? "";

            if (ptype === "bash" || ptype === "shell") {
                if (isDangerousCommand(pcmd)) { output.status = "deny"; return; }
                if (isSafeCommand(pcmd)) { output.status = "allow"; return; }
            }

            output.status = "ask";
        },

        // Inject guidance from routing decision into model context
        "chat.message": async (input, output) => {
            if (output.context) {
                const ctx = output.context;
                if (ctx.__ctxPluginGuidance) {
                    output.parts.push({ type: "text", text: "\n\n" + String(ctx.__ctxPluginGuidance) });
                }
            }
        },
    };
};

export default RoutingPlugin;
