/**
 * transform plugin — opencode plugin
 *
 * Source of truth: ctx_plugin/src/transform.ts
 * Do not edit manually — generated by bin/build-plugins.mjs.
 */

// ─── Imports ─────────────────────────────────────────────────────────────────
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { homedir } from "node:os";
import { mkdirSync, appendFileSync, existsSync, readFileSync } from "node:fs";
// ─── Bun SQLite Infrastructure ────────────────────────────────────────────────
// OpenCode runs on Bun, which bundles bun:sqlite (native FTS5).
// Adapt bun:sqlite API to the same interface used in transform.ts.
function isSQLiteCorruptionError(msg) {
    return (msg.includes("SQLITE_CORRUPT") ||
        msg.includes("SQLITE_NOTADB") ||
        msg.includes("database disk image is malformed") ||
        msg.includes("file is not a database"));
}
function renameCorruptDB(dbPath) {
    const { renameSync } = require("node:fs");
    const ts = Date.now();
    try { renameSync(dbPath, `${dbPath}.corrupt-${ts}`); } catch { /* ok */ }
}
function applyPragmas(db) {
    db.exec("PRAGMA journal_mode = DELETE");
    db.exec("PRAGMA synchronous = NORMAL");
    db.exec("PRAGMA mmap_size = 268435456");
}
function openDatabase(dbPath) {
    const { Database } = require("bun:sqlite");
    let db;
    try {
        db = new Database(dbPath);
    }
    catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (isSQLiteCorruptionError(msg)) {
            renameCorruptDB(dbPath);
            db = new Database(dbPath);
        }
        else {
            throw err;
        }
    }
    applyPragmas(db);
    return db;
}
const _liveDBs = new Set();
process.on("exit", () => {
    for (const db of _liveDBs) {
        try { db.close(); } catch { /* ok */ }
    }
    _liveDBs.clear();
});
function registerDB(db) { _liveDBs.add(db); }
// ─── Config ─────────────────────────────────────────────────────────────────
const DATA_DIR = process.env.TRANSFORM_DATA_DIR
    || resolve(process.cwd(), ".ctx_plugin", "data");
const LOG_DIR = resolve(process.cwd(), ".ctx_plugin", "log");
const LOG_FILE = resolve(LOG_DIR, "transform.log");
function ensureLogDir() {
    try {
        mkdirSync(LOG_DIR, { recursive: true });
    }
    catch { }
}
let _logFileReady = false;
function writeLog(level, ...parts) {
    if (!_logFileReady) {
        ensureLogDir();
        _logFileReady = true;
    }
    const ts = new Date().toISOString().replace("T", " ").replace("Z", "");
    const line = `${ts} [${level}] [Transform] ${parts.join(" ")}\n`;
    try {
        appendFileSync(LOG_FILE, line);
    }
    catch { }
}
const log = {
    info: (...a) => { writeLog("INFO", ...a); _appLog?.("info", a.join(" ")); },
    warn: (...a) => { writeLog("WARN", ...a); _appLog?.("warn", a.join(" ")); },
    error: (...a) => { writeLog("ERROR", ...a); _appLog?.("error", a.join(" ")); },
};
let _appLog = null;
function initAppLogger(client) {
    _appLog = (level, msg) => {
        try {
            client.app.log({ body: { service: "Transform", level, message: msg } });
        }
        catch { /* file log already done above */ }
    };
}
const TOKEN_BUDGET = 8000;
const MAX_HOT_TURNS = 5;
const DECAY_WEIGHTS = {
    distance: 1.0,
    time: 0.3,
    frequency: 0.5,
};
const TOOL_DECAY_MODIFIERS = {
    read: 0.8,
    glob: 0.6,
    grep: 0.7,
    webfetch: 1.5,
};
const CACHEABLE_TOOLS = new Set([
    "read", "glob", "grep", "webfetch",
]);
const SESSION_ID = process.env.SESSION_ID || "default";
// ─── LLM Config ─────────────────────────────────────────────────────────────
function getCtxPluginGlobalDir() {
    if (process.env.CTX_PLUGIN_CONFIG_DIR)
        return process.env.CTX_PLUGIN_CONFIG_DIR;
    if (process.platform === "win32") {
        return resolve(process.env.APPDATA || resolve(homedir(), "AppData", "Roaming"), "ctx_plugin");
    }
    return resolve(homedir(), ".ctx_plugin");
}
function loadLLMConfigFromFile() {
    // Priority: project .ctx_plugin/config.json > project config.json (legacy) > global ~/.ctx_plugin/config.json
    const candidates = [
        resolve(process.cwd(), ".ctx_plugin", "config.json"),
        resolve(process.cwd(), "config.json"),
        resolve(getCtxPluginGlobalDir(), "config.json"),
    ];
    for (const path of candidates) {
        if (!existsSync(path))
            continue;
        try {
            const cfg = JSON.parse(readFileSync(path, "utf-8"));
            if (cfg.llm?.apiKey || cfg.apiKey) {
                return {
                    apiKey: cfg.llm?.apiKey || cfg.apiKey || undefined,
                    baseUrl: cfg.llm?.baseUrl || cfg.baseUrl || undefined,
                    model: cfg.llm?.model || cfg.model || undefined,
                    maxTokens: cfg.llm?.maxTokens || cfg.maxTokens || undefined,
                    temperature: cfg.llm?.temperature || cfg.temperature || undefined,
                };
            }
        }
        catch { /* try next */ }
    }
    return {};
}
const _fileConfig = loadLLMConfigFromFile();
const LLM_CONFIG = {
    apiKey: process.env.CONTEXT_FORGE_LLM_API_KEY || process.env.TRANSFORM_LLM_API_KEY || _fileConfig.apiKey || "placeholder",
    baseUrl: process.env.CONTEXT_FORGE_LLM_BASE_URL || process.env.TRANSFORM_LLM_BASE_URL || _fileConfig.baseUrl || "http://116.204.104.177:8123",
    model: process.env.CONTEXT_FORGE_LLM_MODEL || process.env.TRANSFORM_LLM_MODEL || _fileConfig.model || "GLM-4.7",
    maxTokens: _fileConfig.maxTokens ?? 2048,
    temperature: _fileConfig.temperature ?? 0.3,
};
function validateLLMConfig() {
    if (LLM_CONFIG.apiKey === "placeholder") {
        log.warn("LLM summarization DISABLED (no API key configured)");
        log.warn("Set CONTEXT_FORGE_LLM_API_KEY (+ CONTEXT_FORGE_LLM_BASE_URL) to enable turn summaries");
    }
}
// ─── SQLite Store ────────────────────────────────────────────────────────────
/**
 * Schema is injected at build time from @context-forge/shared-types/schema.
 * See bin/build-plugins.mjs — it replaces __CTX_SUMMARIES_SCHEMA__ with
 * the canonical SUMMARIES_DB_SCHEMA export.
 */
const SCHEMA = `
CREATE TABLE IF NOT EXISTS global_summary_cache (
  content_hash TEXT NOT NULL PRIMARY KEY,
  overview TEXT NOT NULL,
  intent TEXT NOT NULL,
  actions_json TEXT NOT NULL DEFAULT '[]',
  artifacts_json TEXT NOT NULL DEFAULT '[]',
  outcome TEXT NOT NULL DEFAULT 'unknown',
  errors_json TEXT NOT NULL DEFAULT '[]',
  todos_json TEXT NOT NULL DEFAULT '[]',
  confidence REAL NOT NULL DEFAULT 0.5,
  reason TEXT,
  generated_at INTEGER NOT NULL,
  tokens_used INTEGER DEFAULT 0,
  hit_count INTEGER NOT NULL DEFAULT 1,
  last_hit_at INTEGER NOT NULL,
  start_msg_id TEXT NOT NULL,
  end_msg_id TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session_turn_summaries (
  session_id TEXT NOT NULL,
  turn_index INTEGER NOT NULL,
  content_hash TEXT NOT NULL,
  PRIMARY KEY (session_id, turn_index)
);

CREATE INDEX IF NOT EXISTS idx_session_summaries_hash ON session_turn_summaries(content_hash);
CREATE INDEX IF NOT EXISTS idx_session_summaries_session ON session_turn_summaries(session_id);

CREATE VIRTUAL TABLE IF NOT EXISTS summaries_fts USING fts5(
  content_hash UNINDEXED,
  overview,
  intent,
  outcome,
  content='global_summary_cache',
  content_rowid='rowid'
);

CREATE TRIGGER IF NOT EXISTS summaries_ai AFTER INSERT ON global_summary_cache BEGIN
  INSERT INTO summaries_fts(rowid, content_hash, overview, intent, outcome)
  VALUES (new.rowid, new.content_hash, new.overview, new.intent, new.outcome);
END;

CREATE TRIGGER IF NOT EXISTS summaries_ad AFTER DELETE ON global_summary_cache BEGIN
  INSERT INTO summaries_fts(summaries_fts, rowid, content_hash, overview, intent, outcome)
  VALUES ('delete', old.rowid, old.content_hash, old.overview, old.intent, old.outcome);
END;

CREATE TRIGGER IF NOT EXISTS summaries_au AFTER UPDATE ON global_summary_cache BEGIN
  INSERT INTO summaries_fts(summaries_fts, rowid, content_hash, overview, intent, outcome)
  VALUES ('delete', old.rowid, old.content_hash, old.overview, old.intent, old.outcome);
  INSERT INTO summaries_fts(rowid, content_hash, overview, intent, outcome)
  VALUES (new.rowid, new.content_hash, new.overview, new.intent, new.outcome);
END;

CREATE TABLE IF NOT EXISTS turn_messages (
  msg_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  turn_index INTEGER NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  tool_calls TEXT,
  created_at INTEGER NOT NULL,
  seq_in_turn INTEGER NOT NULL,
  PRIMARY KEY (msg_id)
);
CREATE INDEX IF NOT EXISTS idx_turn_messages_lookup ON turn_messages(session_id, turn_index, seq_in_turn);
`;
class SummaryStore {
    db;
    constructor(db) {
        this.db = db;
        this.db.exec(SCHEMA);
    }
    getByHash(contentHash) {
        const stmt = this.db.prepare("SELECT * FROM global_summary_cache WHERE content_hash = ?");
        const row = stmt.get(contentHash);
        if (!row)
            return null;
        this.db.prepare("UPDATE global_summary_cache SET hit_count = hit_count + 1, last_hit_at = ? WHERE content_hash = ?").run(Date.now(), contentHash);
        return this.rowToSummary(row);
    }
    insert(summary, sessionId, contentHash) {
        this.db.prepare(`
      INSERT OR REPLACE INTO global_summary_cache
        (content_hash, overview, intent, actions_json, artifacts_json,
         outcome, errors_json, todos_json, confidence, reason, generated_at,
         tokens_used, last_hit_at, start_msg_id, end_msg_id)
      VALUES
        (?, ?, ?, ?, ?,
         ?, ?, ?, ?, ?,
         ?, ?, ?, ?,
         ?)
    `).run(contentHash, summary.overview, summary.intent, JSON.stringify(summary.actions), JSON.stringify(summary.artifacts), summary.outcome, JSON.stringify(summary.errors), JSON.stringify(summary.todos), summary.confidence, summary.reason || null, summary.generatedAt, summary.tokensUsed || 0, Date.now(), summary.startMsgId, summary.endMsgId);
        this.db.prepare(`
      INSERT OR REPLACE INTO session_turn_summaries
        (session_id, turn_index, content_hash)
      VALUES (?, ?, ?)
    `).run(sessionId, summary.turnIndex, contentHash);
    }
    insertMessages(sessionId, turnIndex, messages) {
        const stmt = this.db.prepare(`
      INSERT OR REPLACE INTO turn_messages
        (msg_id, session_id, turn_index, role, content, tool_calls, created_at, seq_in_turn)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);
        for (let seq = 0; seq < messages.length; seq++) {
            const msg = messages[seq];
            const role = msg?.info?.role || msg?.role || "unknown";
            let textContent = "";
            const toolCalls = [];
            for (const part of msg.parts || []) {
                if (part.type === "text") {
                    textContent += (part.text || "").trim();
                }
                else if (part.type === "tool") {
                    const state = part.state || {};
                    toolCalls.push({
                        name: part.tool || "unknown",
                        input: JSON.stringify(state.input || {}),
                        output: (state.output || "").toString(),
                    });
                }
            }
            stmt.run(`${sessionId}-turn${turnIndex}-seq${seq}`, sessionId, turnIndex, role, textContent, toolCalls.length > 0 ? JSON.stringify(toolCalls) : null, msg?.timestamp || Date.now(), seq);
        }
    }
    search(query, limit = 5) {
        if (!query.trim())
            return [];
        const safe = query.replace(/[^a-zA-Z0-9\u4e00-\u9fff\s]/g, " ").trim();
        if (!safe || safe.length > 200)
            return [];
        const words = safe.split(/\s+/).filter(Boolean);
        if (words.length === 0)
            return [];
        const ftsQuery = words.map((w) => `"${w.replace(/"/g, '""')}"`).join(" OR ");
        try {
            const stmt = this.db.prepare(`
        SELECT * FROM global_summary_cache
        WHERE content_hash IN (
          SELECT content_hash FROM summaries_fts WHERE summaries_fts MATCH ?
        )
        ORDER BY hit_count DESC, last_hit_at DESC
        LIMIT ?
      `);
            const rows = stmt.all(ftsQuery, limit);
            return rows.map((row) => this.rowToSummary(row));
        }
        catch (err) {
            log.warn("search failed:", String(err));
            return [];
        }
    }
    rowToSummary(row) {
        return {
            turnIndex: row.turn_index ?? 0,
            overview: row.overview,
            intent: row.intent,
            actions: safeJsonParse(row.actions_json, []),
            artifacts: safeJsonParse(row.artifacts_json, []),
            outcome: row.outcome,
            errors: safeJsonParse(row.errors_json, []),
            todos: safeJsonParse(row.todos_json, []),
            confidence: row.confidence,
            reason: row.reason || undefined,
            generatedAt: row.generated_at,
            tokensUsed: row.tokens_used,
            startMsgId: row.start_msg_id,
            endMsgId: row.end_msg_id,
        };
    }
}
// Global store instance (initialized lazily — synchronous)
let store = null;
function getStore() {
    if (!store) {
        mkdirSync(DATA_DIR, { recursive: true });
        const dbPath = resolve(DATA_DIR, "summaries.db");
        const db = openDatabase(dbPath);
        registerDB(db);
        store = new SummaryStore(db);
    }
    return store;
}
const SUMMARY_SYSTEM_PROMPT = `你是一个上下文压缩助手。请从对话轮次中提取关键信息，生成结构化摘要。

重要：你没有思考能力，不要输出任何思考过程、推理步骤或解释。直接输出 JSON 结果。

输出要求：
- overview 控制在 20 字以内
- actions 只记录关键步骤，跳过纯探索性调用（read/grep/glob 等），除非结果有特别发现
- artifacts 优先记录 modified/created，read 类型除非有重要发现否则省略
- confidence 反映摘要可信度：对话清晰=0.9, 模糊或结果截断=0.5
- 如果 outcome 不是 success，必须填写 reason 字段

严格按以下 JSON 格式输出，不可省略任何字段：`;
const SUMMARY_USER_PROMPT = `请为以下对话轮次生成摘要：

<turn_messages>
{turn_content}
</turn_messages>

按此 JSON 格式直接输出（不要包含任何其他内容、思考过程或解释）：
{
  "overview": "一句话描述本轮做了什么+结果",
  "intent": "用户的核心需求",
  "actions": [{"tool": "工具名", "target": "操作对象", "description": "动作", "result": "结果"}],
  "artifacts": [{"path": "文件路径", "action": "created|modified|deleted|read", "detail": "变更说明"}],
  "outcome": "success|partial|failure|unknown",
  "errors": ["错误描述"],
  "todos": ["未完成事项"],
  "confidence": 0.0-1.0,
  "reason": "当 outcome!=success 或 confidence<0.7 时的解释"
}`;
function serializeMessages(messages) {
    const lines = [];
    for (const msg of messages) {
        const role = msg?.info?.role || msg?.role || "unknown";
        lines.push(`[${role.toUpperCase()}]`);
        for (const part of msg.parts || []) {
            if (part.type === "text") {
                const text = (part.text || "").trim();
                if (text)
                    lines.push(text);
            }
            else if (part.type === "tool") {
                const toolName = part.tool || "unknown";
                const state = part.state || {};
                const inputStr = JSON.stringify(state.input || {}, null, 2);
                const outputStr = (state.output || "").toString();
                lines.push(`--- tool_call: ${toolName}`);
                lines.push(`input: ${inputStr}`);
                const MAX_OUTPUT_LINES = 60;
                const outputLines = outputStr.split("\n");
                if (outputLines.length > MAX_OUTPUT_LINES) {
                    lines.push(`output (truncated, ${outputLines.length} lines):`, ...outputLines.slice(0, MAX_OUTPUT_LINES), `... [${outputLines.length - MAX_OUTPUT_LINES} more lines]`);
                }
                else {
                    lines.push(`output: ${outputStr || "(empty)"}`);
                }
                lines.push("---");
            }
        }
    }
    return lines.join("\n");
}
async function generateSummary(turnIndex, messages, sessionId, contentHash) {
    if (!LLM_CONFIG.apiKey || LLM_CONFIG.apiKey === "placeholder") {
        log.info(`No LLM API key — summary skipped for turn ${turnIndex}`);
        return null;
    }
    const serializedContent = serializeMessages(messages).slice(0, MAX_SERIALIZED_SIZE);
    const requestMessages = [
        { role: "system", content: SUMMARY_SYSTEM_PROMPT },
        { role: "user", content: SUMMARY_USER_PROMPT.replace("{turn_content}", serializedContent) },
    ];
    try {
        const url = `${LLM_CONFIG.baseUrl.replace(/\/$/, "")}/v1/chat/completions`;
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 60_000);
        let res;
        try {
            res = await fetch(url, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${LLM_CONFIG.apiKey}`,
                },
                signal: controller.signal,
                body: JSON.stringify({
                    model: LLM_CONFIG.model,
                    messages: requestMessages,
                    max_tokens: LLM_CONFIG.maxTokens,
                    temperature: LLM_CONFIG.temperature,
                }),
            });
        }
        finally {
            clearTimeout(timeout);
        }
        if (!res.ok) {
            log.error(`LLM API error ${res.status} for turn ${turnIndex}`);
            return null;
        }
        const data = await Promise.race([
            res.json(),
            new Promise((_, reject) => setTimeout(() => reject(new Error("LLM response JSON parse timeout")), 30_000)),
        ]);
        const raw = data.choices?.[0]?.message?.content || "";
        const parsed = parseLLMResponse(raw);
        const summary = {
            turnIndex,
            overview: parsed.overview,
            intent: parsed.intent,
            actions: parsed.actions,
            artifacts: parsed.artifacts,
            outcome: parsed.outcome,
            errors: parsed.errors,
            todos: parsed.todos,
            confidence: parsed.confidence,
            reason: parsed.reason,
            generatedAt: Date.now(),
            tokensUsed: data.usage?.total_tokens || 0,
            startMsgId: `turn-${turnIndex}-start`,
            endMsgId: `turn-${turnIndex}-end`,
        };
        const db = await getStore();
        db.insert(summary, sessionId, contentHash);
        db.insertMessages(sessionId, turnIndex, messages);
        log.info(`Summary generated for turn ${turnIndex}: ${summary.overview}`);
        return summary;
    }
    catch (err) {
        log.error(`LLM call failed for turn ${turnIndex}:`, String(err));
        return null;
    }
}
function parseLLMResponse(raw) {
    const defaultReturn = {
        overview: "(解析失败)",
        intent: "",
        actions: [],
        artifacts: [],
        outcome: "unknown",
        errors: [],
        todos: [],
        confidence: 0.1,
        reason: `LLM 返回格式无法解析: ${raw.slice(0, 200)}`,
    };
    const match = raw.match(/```json\s*([\s\S]*?)\s*```/) ?? raw.match(/(\{[\s\S]*\})/);
    if (!match)
        return defaultReturn;
    try {
        const parsed = JSON.parse(match[1]);
        return {
            overview: String(parsed.overview || "").slice(0, 100),
            intent: String(parsed.intent || ""),
            actions: Array.isArray(parsed.actions) ? parsed.actions : [],
            artifacts: Array.isArray(parsed.artifacts) ? parsed.artifacts : [],
            outcome: ["success", "partial", "failure", "unknown"].includes(parsed.outcome)
                ? parsed.outcome : "unknown",
            errors: Array.isArray(parsed.errors) ? parsed.errors : [],
            todos: Array.isArray(parsed.todos) ? parsed.todos : [],
            confidence: Math.max(0, Math.min(1, parseFloat(parsed.confidence) || 0.5)),
            reason: parsed.reason,
        };
    }
    catch {
        return defaultReturn;
    }
}
// ─── Compression Logic ──────────────────────────────────────────────────────
// ─── Helpers ─────────────────────────────────────────────────────────────────
const MAX_SERIALIZED_SIZE = 50_000;
function deepClone(obj) {
    // Fast path for plain objects/arrays of primitives — avoids JSON roundtrip
    try {
        return structuredClone(obj);
    }
    catch {
        // structuredClone throws on circular refs or non-serializable values
        // Fall back to JSON roundtrip (handles circular by throwing)
        return JSON.parse(JSON.stringify(obj));
    }
}
function safeJsonParse(json, fallback) {
    try {
        return JSON.parse(json);
    }
    catch {
        return fallback;
    }
}
// Fast token estimator — avoids full JSON.stringify of every message on each call.
// Tokens ≈ chars / 4 is accurate enough for compression decisions.
function estimateTokens(messages) {
    let total = 0;
    for (const m of messages) {
        if (!m)
            continue;
        // Use info + parts path for new format, role/parts for old format
        const parts = m.parts || [];
        for (const p of parts) {
            if (typeof p?.text === "string")
                total += p.text.length;
            else if (typeof p?.output === "string")
                total += p.output.length;
            else if (typeof p === "string")
                total += p.length;
        }
    }
    return Math.ceil(total / 4);
}
function getRole(msg) {
    return msg?.info?.role || msg?.role || "";
}
// Fast hash for message deduplication — extracts only the meaningful content
// to avoid the cost of full JSON.stringify on large message arrays.
function hashMessages(messages) {
    // Only hash role + text content — skip metadata, timestamps, tokens, etc.
    let input = "";
    for (const m of messages) {
        input += (m?.info?.role || m?.role || "") + "|";
        const parts = m?.parts || [];
        for (const p of parts) {
            if (p?.type === "text")
                input += p.text ?? "";
            else if (p?.type === "tool")
                input += (p?.tool ?? "") + "|" + (p?.state?.input ? JSON.stringify(p.state.input) : "");
        }
        input += "\n";
    }
    return createHash("sha256").update(input).digest("hex");
}
function splitIntoTurns(messages) {
    if (messages.length === 0)
        return [];
    const turns = [];
    let currentTurnStart = 0;
    for (let i = 1; i < messages.length; i++) {
        const prevMsg = messages[i - 1];
        const currMsg = messages[i];
        const prevRole = getRole(prevMsg);
        const currRole = getRole(currMsg);
        if (prevRole !== "user" && currRole === "user") {
            const turnMessages = messages.slice(currentTurnStart, i);
            turns.push({
                index: turns.length,
                startIdx: currentTurnStart,
                endIdx: i,
                messages: turnMessages,
                isCurrent: false,
                messageCount: turnMessages.length,
                tokenEstimate: estimateTokens(turnMessages),
                contentHash: hashMessages(turnMessages),
                summaryStatus: "pending",
            });
            currentTurnStart = i;
        }
    }
    const finalMessages = messages.slice(currentTurnStart);
    turns.push({
        index: turns.length,
        startIdx: currentTurnStart,
        endIdx: messages.length,
        messages: finalMessages,
        isCurrent: true,
        messageCount: finalMessages.length,
        tokenEstimate: estimateTokens(finalMessages),
        contentHash: hashMessages(finalMessages),
        summaryStatus: "pending",
    });
    return turns;
}
function buildToolKey(prefix, primaryKey, primaryValue, input) {
    const params = Object.entries(input)
        .filter(([k, v]) => k !== primaryKey && v !== undefined && v !== "")
        .map(([k, v]) => `${k}=${v}`).sort().join(";");
    return params ? `${prefix}:${primaryValue};${params}` : `${prefix}:${primaryValue}`;
}
function getToolOutputKey(toolName, state) {
    const input = state?.input || {};
    const tool = toolName.toLowerCase();
    switch (tool) {
        case "read": {
            const filePath = input.filePath || input.file || input.path || "";
            const cleanInput = { ...input, filePath };
            delete cleanInput.file;
            delete cleanInput.path;
            return buildToolKey("file", "filePath", filePath, cleanInput);
        }
        case "grep":
            return buildToolKey("grep", "pattern", input.pattern || "", input);
        case "glob":
            return buildToolKey("glob", "pattern", input.pattern || "", input);
        case "webfetch":
            return buildToolKey("url", "url", input.url || "", input);
        default:
            return null;
    }
}
function calculateDecayScore(entry, currentTurnIdx) {
    const { distance: wDist, time: wTime, frequency: wFreq } = DECAY_WEIGHTS;
    const turnDistance = currentTurnIdx - Math.floor(entry.lastSeenTurnIdx / 10);
    const distanceScore = Math.min(turnDistance / 3, 5);
    const timeAgeMinutes = (Date.now() - entry.timestamp) / 60000;
    const timeScore = Math.log2(timeAgeMinutes + 1) * wTime;
    const frequencyScore = Math.log2(entry.callCount + 1) * wFreq;
    const toolModifier = TOOL_DECAY_MODIFIERS[entry.toolType] || 1.0;
    const baseScore = distanceScore * wDist + timeScore - frequencyScore;
    return Math.max(0, Math.min(baseScore * toolModifier, 10));
}
function getCompressionLevel(score) {
    if (score < 2)
        return "full";
    if (score < 5)
        return "summary";
    if (score < 8)
        return "placeholder";
    return "minimal";
}
function compressToolOutput(toolName, state, level) {
    const input = state?.input || {};
    const output = state?.output || "";
    const tool = toolName.toLowerCase();
    switch (tool) {
        case "read": {
            const filePath = input.filePath || input.file || input.path || "?";
            const lines = output.split("\n");
            const lineCount = lines.length;
            switch (level) {
                case "full": return output;
                case "summary": return `[COMPRESSED: read "${filePath}"]\n${[
                    ...lines.slice(0, 3),
                    `  ... ${Math.max(0, lineCount - 6)} more lines ...`,
                    ...lines.slice(-3),
                ].join("\n")}`;
                case "placeholder": return `[COMPRESSED: read "${filePath}" — ${lineCount} lines]`;
                case "minimal": return `[COMPRESSED: read "${filePath}"]`;
            }
        }
        case "glob": {
            const pattern = input.pattern || "?";
            const lines = output.split("\n").filter(Boolean);
            const count = lines.length;
            switch (level) {
                case "full": return output;
                case "summary": return `[COMPRESSED: glob "${pattern}"] — ${count} matches: ${lines.slice(0, 5).join(", ")}${count > 5 ? ` ... +${count - 5} more` : ""}`;
                case "placeholder": return `[COMPRESSED: glob "${pattern}" — ${count} matches]`;
                case "minimal": return `[COMPRESSED: glob "${pattern}"]`;
            }
        }
        case "grep": {
            const pattern = input.pattern || "?";
            const lines = output.split("\n").filter(Boolean);
            const count = lines.length;
            switch (level) {
                case "full": return output;
                case "summary": return `[COMPRESSED: grep "${pattern}"] — ${count} matches: ${lines.slice(0, 5).join(" | ")}${count > 5 ? ` ... +${count - 5} more` : ""}`;
                case "placeholder": return `[COMPRESSED: grep "${pattern}" — ${count} matches]`;
                case "minimal": return `[COMPRESSED: grep "${pattern}"]`;
            }
        }
        case "webfetch": {
            const url = input.url || "?";
            const size = new TextEncoder().encode(output).length;
            switch (level) {
                case "full": return output;
                case "summary": return `[COMPRESSED: webfetch "${url}"]\n${output.slice(0, 200)}...`;
                case "placeholder": return `[COMPRESSED: webfetch "${url}" — ${size} bytes]`;
                case "minimal": return `[COMPRESSED: webfetch "${url}"]`;
            }
        }
        default:
            return `[COMPRESSED: ${toolName} — output truncated]`;
    }
}
function buildCompressedMessagesForHotTurn(turn, toolOutputs, currentTurnIdx) {
    const result = [];
    for (const msg of turn.messages) {
        const role = getRole(msg);
        if (role !== "assistant") {
            result.push(deepClone(msg));
            continue;
        }
        const cloned = deepClone(msg);
        for (const part of cloned.parts || []) {
            if (part.type !== "tool" || part.state?.status !== "completed")
                continue;
            const toolName = part.tool || "";
            if (!CACHEABLE_TOOLS.has(toolName))
                continue;
            const key = getToolOutputKey(toolName, part.state);
            if (!key)
                continue;
            const entry = toolOutputs.get(key);
            if (!entry)
                continue;
            const score = calculateDecayScore(entry, currentTurnIdx);
            const level = getCompressionLevel(score);
            if (level !== "full") {
                part.state.output = compressToolOutput(toolName, part.state, level);
            }
        }
        result.push(cloned);
    }
    return result;
}
function buildSummaryReplacement(turn) {
    const s = turn.summary;
    const timestamp = new Date(turn.messages[0]?.timestamp ?? Date.now()).toLocaleString();
    return [
        {
            info: { role: "user", __compressed: "summary", turnIndex: turn.index },
            parts: [{
                    type: "text",
                    text: `=== Turn ${turn.index} Summary (${timestamp}) ===\nCompressed: ${turn.messageCount} msgs, ~${turn.tokenEstimate} tokens.`,
                }],
        },
        {
            info: { role: "assistant", __compressed: "summary", turnIndex: turn.index },
            parts: [{
                    type: "text",
                    text: s
                        ? [
                            `Turn ${turn.index} Summary:`,
                            `Overview: ${s.overview}`,
                            s.intent ? `Intent: ${s.intent}` : null,
                            s.actions.length > 0 ? `Actions: ${s.actions.map((a) => `${a.tool}(${a.target})`).join(", ")}` : null,
                            s.artifacts.length > 0 ? `Artifacts: ${s.artifacts.map((a) => `${a.action} ${a.path}`).join(", ")}` : null,
                            `Outcome: ${s.outcome}`,
                        ].filter(Boolean).join("\n")
                        : `(Summary not yet generated)`,
                }],
        },
    ];
}
function buildPlaceholderReplacement(turn) {
    return [{
            info: { role: "user", __compressed: "placeholder", turnIndex: turn.index },
            parts: [{
                    type: "text",
                    text: `=== Turn ${turn.index} (${turn.messageCount} msgs, ~${turn.tokenEstimate} tokens) ===\n[Compressed]`,
                }],
        }];
}
function buildCompressedMessages(turns, toolOutputs) {
    const completedTurns = turns.filter((t) => !t.isCurrent);
    const currentTurn = turns.find((t) => t.isCurrent);
    const reservedForCurrent = currentTurn ? estimateTokens(currentTurn.messages) : 0;
    const availableBudget = TOKEN_BUDGET - reservedForCurrent;
    const sourceTokens = estimateTokens(turns.flatMap((t) => t.messages));
    if (availableBudget <= 0) {
        return {
            messages: currentTurn ? [...currentTurn.messages] : [],
            sourceTokens,
            compressedTokens: sourceTokens,
            reduction: "0%",
        };
    }
    const keptMessages = [];
    const replacedTurns = [];
    let usedTokens = 0;
    for (const turn of [...completedTurns].reverse()) {
        const compressed = buildCompressedMessagesForHotTurn(turn, toolOutputs, turns.length);
        const tokens = estimateTokens(compressed);
        if (usedTokens + tokens <= availableBudget) {
            keptMessages.unshift(...compressed);
            usedTokens += tokens;
        }
        else {
            replacedTurns.unshift(turn);
        }
    }
    const result = [];
    for (const turn of replacedTurns) {
        if (turn.summaryStatus === "done" && turn.summary) {
            result.push(...buildSummaryReplacement(turn));
        }
        else {
            result.push(...buildPlaceholderReplacement(turn));
        }
    }
    result.push(...keptMessages);
    if (currentTurn) {
        result.push(...currentTurn.messages);
    }
    const compressedTokens = estimateTokens(result);
    const reduction = sourceTokens > 0
        ? `${((1 - compressedTokens / sourceTokens) * 100).toFixed(1)}%`
        : "0%";
    return { messages: result, sourceTokens, compressedTokens, reduction };
}
// ─── Session Store (in-memory) ───────────────────────────────────────────────
const sessions = new Map();
const inFlightSummaries = new Set();
const MAX_SESSION_AGE_MS = 30 * 60 * 1000; // 30 minutes
const SESSION_CLEANUP_INTERVAL = 5 * 60 * 1000; // 5 minutes
function cleanupSessions() {
    const now = Date.now();
    for (const [id, store] of sessions) {
        const lastActivity = store.turns[store.turns.length - 1]?.messages[0]?.timestamp || 0;
        if (now - lastActivity > MAX_SESSION_AGE_MS) {
            sessions.delete(id);
        }
    }
}
// Run cleanup periodically
setInterval(cleanupSessions, SESSION_CLEANUP_INTERVAL);
function updateToolOutputIndex(messages, toolOutputs) {
    for (let i = 0; i < messages.length; i++) {
        const msg = messages[i];
        if (getRole(msg) !== "assistant")
            continue;
        for (const part of msg.parts || []) {
            if (part.type !== "tool" || part.state?.status !== "completed")
                continue;
            const toolName = part.tool || "";
            if (!CACHEABLE_TOOLS.has(toolName))
                continue;
            const key = getToolOutputKey(toolName, part.state);
            if (!key)
                continue;
            const output = part.state.output || "";
            if (toolOutputs.has(key)) {
                const entry = toolOutputs.get(key);
                entry.lastSeenTurnIdx = Math.floor(i / 10);
                entry.callCount++;
                if (entry.output !== output)
                    entry.output = output;
            }
            else {
                toolOutputs.set(key, {
                    key,
                    toolType: toolName,
                    output,
                    timestamp: Date.now(),
                    lastSeenTurnIdx: Math.floor(i / 10),
                    callCount: 1,
                });
            }
        }
    }
}
async function syncSession(sessionId, messages) {
    if (!Array.isArray(messages)) {
        log.error("Expected messages to be array");
        return { messages: [], sourceTokens: 0, compressedTokens: 0, reduction: "0%" };
    }
    let store = sessions.get(sessionId);
    if (!store) {
        store = {
            source: [],
            turns: [],
            toolOutputs: new Map(),
        };
        sessions.set(sessionId, store);
    }
    updateToolOutputIndex(messages, store.toolOutputs);
    store.source = messages;
    store.turns = splitIntoTurns(messages);
    const completedTurns = store.turns.filter((t) => !t.isCurrent);
    for (const turn of completedTurns) {
        if (turn.summaryStatus !== "pending")
            continue;
        const db = await getStore();
        const cached = db.getByHash(turn.contentHash);
        if (cached) {
            turn.summary = cached;
            turn.summaryStatus = "done";
        }
        else {
            triggerAsyncSummary(sessionId, turn).catch(() => { });
        }
    }
    const { messages: compressed, sourceTokens, compressedTokens, reduction } = buildCompressedMessages(store.turns, store.toolOutputs);
    log.info(`session=${sessionId.slice(0, 8)}.. turns=${store.turns.length} ` +
        `tokens=${sourceTokens}→${compressedTokens} (${reduction})`);
    return { messages: compressed, sourceTokens, compressedTokens, reduction };
}
async function triggerAsyncSummary(sessionId, turn) {
    const key = `${sessionId}:${turn.contentHash}`;
    if (inFlightSummaries.has(key))
        return;
    inFlightSummaries.add(key);
    turn.summaryStatus = "generating";
    try {
        const summary = await generateSummary(turn.index, turn.messages, sessionId, turn.contentHash);
        if (summary) {
            turn.summary = summary;
            turn.summaryStatus = "done";
        }
        else {
            turn.summaryStatus = "unavailable";
        }
        for (const [, s] of sessions) {
            const t = s.turns.find((x) => x.index === turn.index && !x.isCurrent && x.contentHash === turn.contentHash);
            if (t && t !== turn) {
                t.summary = summary || t.summary;
                t.summaryStatus = summary ? "done" : "unavailable";
            }
        }
    }
    catch {
        turn.summaryStatus = "unavailable";
    }
    finally {
        inFlightSummaries.delete(key);
    }
}
// ─── History Detection ───────────────────────────────────────────────────────
function detectHistoryQuery(parts) {
    let text = "";
    for (const p of parts) {
        if (p?.type === "text")
            text += p.text ?? "";
    }
    text = text.toLowerCase().trim();
    if (!text)
        return null;
    const patterns = [
        /\b(earlier|before|previously|last time|last session|last I|revisit|follow up)\b/,
        /\b(what did I do|what was I working on|show me my|continue that|repeat)\b/,
        /\b(that|this|it).{0,30}(we|I|you).{0,30}(did|made|created|changed|working)\b/i,
        /(?:^|[^a-zA-Z0-9])(之前|上次|之前的|之前做的|那个项目|继续之前|回顾)(?:$|[^a-zA-Z0-9])/,
        /(?:^|[^a-zA-Z0-9])(我之前|我上次|我们之前|它之前|那个文件|那行代码|继续做)(?:$|[^a-zA-Z0-9])/,
        /(?:^|[^a-zA-Z0-9])(我做了什么|我在做什么|做了什么东西|接着之前)(?:$|[^a-zA-Z0-9])/,
    ];
    for (const p of patterns) {
        if (p.test(text))
            return text;
    }
    if (text.length < 50 &&
        /(?:^|[^a-zA-Z0-9])(this|that|it|这里|那里|这个|那个|它|那)(?:$|[^a-zA-Z0-9])/.test(text) &&
        !/(?:^|[^a-zA-Z0-9])(是什么|怎么|help me|what is)(?:$|[^a-zA-Z0-9])/.test(text)) {
        return text;
    }
    return null;
}
// ─── Session Snapshot from DB1 ──────────────────────────────────────────────
/**
 * Load the latest resume snapshot from the session DB (DB1).
 * Best-effort — returns "" if DB1 doesn't exist or is unreadable.
 *
 * The session DB path follows the same convention as
 * mcp_ctx_tool's session-db.ts: ~/.local/share/ctx_plugin/sessions/<hash>.db
 */
async function loadSessionSnapshot() {
    try {
        const hash = createHash("sha256")
            .update(process.cwd().toLowerCase())
            .digest("hex")
            .slice(0, 16);
        const sessionsDir = process.env.CTX_PLUGIN_DATA_DIR
            || (process.env.XDG_DATA_HOME
                ? resolve(process.env.XDG_DATA_HOME, "ctx_plugin")
                : resolve(homedir(), ".local", "share", "ctx_plugin"));
        const dbPath = resolve(sessionsDir, "sessions", `${hash}.db`);
        if (!existsSync(dbPath))
            return "";
        const { Database } = require("bun:sqlite");
        const sessionDb = new Database(dbPath);
        try {
            const stmt = sessionDb.prepare("SELECT id, snapshot FROM session_resume WHERE consumed = 0 ORDER BY created_at DESC LIMIT 1");
            const row = stmt.get();
            if (!row?.snapshot || row.id == null) {
                sessionDb.close();
                return "";
            }
            sessionDb.prepare("UPDATE session_resume SET consumed = 1 WHERE id = ?").run(row.id);
            const result = row.snapshot;
            sessionDb.close();
            return result;
        }
        catch {
            try {
                sessionDb.close();
            }
            catch { /* ignore */ }
            return "";
        }
    }
    catch {
        return "";
    }
}
// ─── Plugin ─────────────────────────────────────────────────────────────────
validateLLMConfig();
export const TransformPlugin = async ({ client }) => {
    initAppLogger(client);
    log.info(`Session started, data dir: ${DATA_DIR}`);
    return {
        "experimental.chat.messages.transform": async (_input, output) => {
            try {
                if (!output?.messages || !Array.isArray(output.messages))
                    return;
                const rawMessages = output.messages;
                // Normalize: SDK gives {info, parts}[] — convert to internal format {info, parts}
                // for use by splitIntoTurns / getRole / etc.
                const messages = rawMessages.map((m) => ({
                    info: m.info ?? {},
                    parts: m.parts ?? [],
                }));
                if (messages.length === 0)
                    return;
                const sessionId = SESSION_ID;
                // Step 1: Compress message history
                const { messages: compressed, sourceTokens, compressedTokens, reduction } = await syncSession(sessionId, messages);
                // Normalize compressed output back to SDK format {info, parts}[]
                const sdkMessages = compressed.map((m) => ({
                    info: m.info ?? {},
                    parts: m.parts ?? [],
                }));
                output.messages.splice(0, output.messages.length, ...sdkMessages);
                // Step 2: Inject history context if needed
                const lastMsg = messages[messages.length - 1];
                if (!lastMsg || getRole(lastMsg) !== "user")
                    return;
                const query = detectHistoryQuery(lastMsg.parts || []);
                if (!query)
                    return;
                const db = getStore();
                const results = db.search(query, 3);
                let sessionSnapshot = "";
                try {
                    sessionSnapshot = await loadSessionSnapshot();
                }
                catch {
                    // best-effort — DB1 may not be available
                }
                if (results.length === 0 && !sessionSnapshot)
                    return;
                const contextParts = [];
                if (sessionSnapshot) {
                    contextParts.push(sessionSnapshot);
                }
                if (results.length > 0) {
                    contextParts.push(`=== Historical Context (LLM Summaries) ===\n` +
                        results.map((s) => `[Turn ${s.turnIndex}] ${s.overview}${s.intent ? ` | Intent: ${s.intent}` : ""}${s.outcome ? ` | ${s.outcome}` : ""}`).join("\n"));
                }
                const injected = contextParts.map((text) => ({
                    info: { role: "system", __transformInjected: true },
                    parts: [{ type: "text", text }],
                }));
                const insertAt = messages.length - 1;
                output.messages.splice(insertAt, 0, ...injected);
                log.info(`Injected ${injected.length} history blocks (DB3 summaries + ${sessionSnapshot ? "DB1 snapshot" : "no snapshot"}), ` +
                    `compression=${sourceTokens}→${compressedTokens} (${reduction})`);
            }
            catch (err) {
                log.error("Transform hook failed:", String(err));
                // Do NOT re-throw — prevents opencode from crashing
            }
        },
    };
};
export default TransformPlugin;
